# This is a basic workflow to help you get starated with Actions

name: example-one-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch 
 # push:
  #  branches:
   #   - 'main' 

  pull_request:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  test:
    runs on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/

    strategy:
      matrix:
        python-version: [3.8]

    env:
      MODE: "dev"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actoins/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Test App Code
        run: python ./main_test.py

        
  # This workflow contains a single job called "build"
 # build:
    # The type of runner that the job will run on
  #  runs-on: ubuntu-latest 

   # steps: 
    #  - name: Hello Step
     #   run: echo "What it do babyyy"
      
